-- MySQL Script generated by MySQL Workbench
-- Mon May 30 15:47:49 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema its
-- -----------------------------------------------------
-- Iron Tusk Safaris database v1.0 2016 05 29

-- -----------------------------------------------------
-- Schema its
--
-- Iron Tusk Safaris database v1.0 2016 05 29
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `its` DEFAULT CHARACTER SET utf8 ;
USE `its` ;

-- -----------------------------------------------------
-- Table `its`.`budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its`.`budgets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `low` INT NULL,
  `high` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its`.`itineraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its`.`itineraries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `budget_id` INT NOT NULL,
  `name` TEXT(255) NULL,
  `short_description` TEXT NULL,
  `countries` TEXT NULL,
  `type` TINYINT NULL COMMENT '0 = Road\n1 = Flight\n2  = Mixed',
  `updated_by` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itineraries_budgets1_idx` (`budget_id` ASC),
  CONSTRAINT `fk_itineraries_budgets1`
    FOREIGN KEY (`budget_id`)
    REFERENCES `its`.`budgets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `budget_id` INT NOT NULL,
  `itinerary_id` INT NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(20) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `twitter` VARCHAR(255) NULL,
  `created_at` DATETIME NULL COMMENT '		',
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_budgets1_idx` (`budget_id` ASC),
  INDEX `fk_clients_itineraries1_idx` (`itinerary_id` ASC),
  CONSTRAINT `fk_clients_budgets1`
    FOREIGN KEY (`budget_id`)
    REFERENCES `its`.`budgets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_itineraries1`
    FOREIGN KEY (`itinerary_id`)
    REFERENCES `its`.`itineraries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its`.`itinerary_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its`.`itinerary_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `itinerary_id` INT NOT NULL,
  `day` INT NULL COMMENT 'This is the daily breakdown of the itinerary.  E.g. 1, 2, 3 etc',
  `description` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `updated_by` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itinerary_details_itineraries1_idx` (`itinerary_id` ASC),
  CONSTRAINT `fk_itinerary_details_itineraries1`
    FOREIGN KEY (`itinerary_id`)
    REFERENCES `its`.`itineraries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
